### ISSUE TITLE
Stremio

### ISSUE THREAD

**Issue by napacia** [Flixclusive/flx-providers#4]
does torrentio addon without rd work? cuz mine says can't find a link. just wanna know

**Comment by rhenwinch** [comment]
Hi! Unfortunately, no.

Media3/ExoPlayer doesn't support torrent streaming. Some torrent streaming libraries are outdated for android. Though, you could just use Stremio instead.

Exoplayer torrent streaming should be for future updates, but Im not so sure where to start from that currently since theres a lack of community support regarding the matter.
